// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7JcQaaAWBbf1B4qVK68c6X0wrWiPXiMs',
    appId: '1:540355122026:web:c8ec6024aa23610d5fcb13',
    messagingSenderId: '540355122026',
    projectId: 'gocampus-2a174',
    authDomain: 'gocampus-2a174.firebaseapp.com',
    storageBucket: 'gocampus-2a174.firebasestorage.app',
    measurementId: 'G-SJWLK9DCLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2As3cQwcE5ornsqQbIylBPt3_w1l9mxw',
    appId: '1:540355122026:android:8efb90dd6aabf2d25fcb13',
    messagingSenderId: '540355122026',
    projectId: 'gocampus-2a174',
    storageBucket: 'gocampus-2a174.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClBMb78RPBPmKDBuklT0lKwvxqee5vJf4',
    appId: '1:540355122026:ios:fd6ba202e1c73edf5fcb13',
    messagingSenderId: '540355122026',
    projectId: 'gocampus-2a174',
    storageBucket: 'gocampus-2a174.firebasestorage.app',
    iosBundleId: 'com.example.goCampus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClBMb78RPBPmKDBuklT0lKwvxqee5vJf4',
    appId: '1:540355122026:ios:fd6ba202e1c73edf5fcb13',
    messagingSenderId: '540355122026',
    projectId: 'gocampus-2a174',
    storageBucket: 'gocampus-2a174.firebasestorage.app',
    iosBundleId: 'com.example.goCampus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7JcQaaAWBbf1B4qVK68c6X0wrWiPXiMs',
    appId: '1:540355122026:web:a45d767e780b7e2a5fcb13',
    messagingSenderId: '540355122026',
    projectId: 'gocampus-2a174',
    authDomain: 'gocampus-2a174.firebaseapp.com',
    storageBucket: 'gocampus-2a174.firebasestorage.app',
    measurementId: 'G-G2583LF4EY',
  );
}
